name: quran_app
description: "A Qur'an app built with flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sqflite: ^2.4.0
  shared_preferences: ^2.3.3
  path: ^1.9.0
  flexible_scrollbar: ^0.1.3
  searchfield: ^1.2.4
  flutter_svg: ^2.0.17
#  flutter_statusbarcolor_ns: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/documents/

  fonts:
    - family: varela-round.regular
      fonts:
        - asset: assets/fonts/varela-round.regular.ttf
    - family: 110_Besmellah Normal
      fonts:
        - asset: assets/fonts/110_Besmellah Normal.ttf
    - family: Rounded_Elegance
      fonts:
        - asset: assets/fonts/Rounded_Elegance.ttf
    - family: Al Majeed Quranic Font_shiped
      fonts:
        - asset: assets/fonts/Al Majeed Quranic Font_shiped.ttf
    - family: Diwanltr
      fonts:
        - asset: assets/fonts/Diwanltr.ttf
    - family: Bismillah Script
      fonts:
        - asset: assets/fonts/Bismillah Script.ttf
    - family: KFGQPC WARSH Uthmanic Script Regular
      fonts:
        - asset: assets/fonts/KFGQPC WARSH Uthmanic Script.ttf
    - family: KFGQPC HafsEx1 Uthmanic Script
      fonts:
        - asset: assets/fonts/KFGQPC HafsEx1 Uthmanic Script.ttf
    - family: Muhammadi Quranic Font
      fonts:
        - asset: assets/fonts/Muhammadi Quranic Font.ttf
    - family: Al_Mushaf
      fonts:
        - asset: assets/fonts/Al_Mushaf.ttf
    - family: NotoNaskhArabic-Medium
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: qalammajeed3
      fonts:
        - asset: assets/fonts/qalammajeed3.ttf
    - family: hafs
      fonts:
        - asset: assets/fonts/hafs.ttf
    - family: rr
      fonts:
        - asset: assets/fonts/rr.ttf
    - family: rc
      fonts:
        - asset: assets/fonts/rc.ttf
    - family: rsc
      fonts:
        - asset: assets/fonts/rsc.ttf
    - family: bismillah
      fonts:
        - asset: assets/fonts/bismillah.ttf
    - family: times
      fonts:
        - asset: assets/fonts/times.ttf
